---
include:
  - board: nice_nano_v2
    shield: sofle_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: sofle_right nice_view_adapter nice_view
  # - board: nrfmicro_13
  #   shield: sofle_dongle
  - board: nrfmicro_13
    shield: settings_reset
  - board: nice_nano_v2
    shield: settings_reset