draw_config:
  shrink_wide_legends: 5
parse_config:
  modifier_fn_map:
    left_ctrl: ^
    right_ctrl: ^
    left_shift: ⇧
    right_shift: ⇧
    left_alt: ⌥
    right_alt: ⌥
    left_gui: ⌘
    right_gui: ⌘
    keycode_combiner: '{mods}{key}'
    mod_combiner: '{mod_1}{mod_2}'
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  zmk_keycode_map:
    LEFT_SHIFT: ⇧
    CLCK: 🄰
    BACKSPACE: ⌫
    BSPC: ⌫
    DELETE: ⌦
    LALT: ⌥
    LEFT_COMMAND: ⌘
    LEFT_CONTROL: ^
    UP_ARROW: ▲
    DOWN_ARROW: ▼
    LEFT_ARROW: ◀
    RIGHT_ARROW: ▶
    UP: ▲
    DOWN: ▼
    LEFT: ◀
    RIGHT: ▶
    ESCAPE: 'ESC'
    ENTER: ↵
    TAB: ⇥
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    APOSTROPHE: ''''
    APOS: ''''
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
