manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: lennyitb
      url-base: https://github.com/lennyitb
    - name: seanuleh
      url-base: https://github.com/seanuleh
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-layer-report
      remote: seanuleh
      revision: main
  self:
    path: config
