name: Build Firmware

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  layout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - run: |
          go install github.com/mrmarble/zmk-viewer/cmd/zmk-viewer@latest
          zmk-viewer generate -f ./config/sofled.keymap -l ./config/info.json layout -s
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'layout.png'
          commit_message: Update layout image [skip ci]